edition = "2021"
force_explicit_abi = true
hard_tabs = false
match_block_trailing_comma = true
max_width = 80
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = false

## nightly channel only
# comment_width = 120 # same as max_width
# condense_wildcard_suffixes = true
# format_code_in_doc_comments = true
# format_strings = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Module"
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = true
# wrap_comments = true
