[build]
rustflags = [
  ## Warning ##
  "-Dclippy::pedantic",
  "-Dclippy::restriction",
  "-Dclippy::nursery",
  # "-Dclippy::cargo",
  ## Conflicts ##
  "-Aclippy::blanket_clippy_restriction_lints", # clippy::restriction               - can't enable clippy::restriction if this is enabled
  "-Aclippy::implicit_return",                  # clippy::needless-return           - remove return keyword when not needed
  "-Aclippy::pub-with-shorthand",               # clippy::pub-without-shorthand     - pub(<scope>) instead of pub(in <scope>)
  ## Allowed ##
  "-Aclippy::missing_trait_methods",            # convenience
  "-Aclippy::question_mark_used",               # convenience
  ## Maybe remove one day ##
  "-Aclippy::missing_docs_in_private_items",
]
